In [7]:
import pandas as pd
import numpy as np
data=[1,2,3,4]
dict={1:"a",2:"b",3:"c"}
tuple=(1,2,3,4,5)
p=pd.Series(data,['A','B','C','D'])
d=pd.Series(dict)
t=pd.Series(tuple)
print(p)
print(d)
print(t)

A    1
B    2
C    3
D    4
dtype: int64
1    a
2    b
3    c
dtype: object
0    1
1    2
2    3
3    4
4    5
dtype: int64

In [10]:
data=[1,2,3,4]
p=pd.Series(data,['A','B','C','D'],name='Number',dtype="float")
print(p)

A    1.0
B    2.0
C    3.0
D    4.0
Name: Number, dtype: float64

In [14]:
data=pd.Series(5,index=[0,1,2,3,4,5])
print(data)

0    5
1    5
2    5
3    5
4    5
5    5
dtype: int64

In [30]:
data=pd.Series([35,70,85,77,87],['A','B','C','D','E'],name="Number",dtype="float")
print(data)
print(data.values)
print(data.index)
print(data.name)
print(data.hasnans)#checks NaN values
print(data.shape)
print(data.size)
print(data.ndim)
print(data.dtype)
print(data.is_unique)

A    35.0
B    70.0
C    85.0
D    77.0
E    87.0
Name: Number, dtype: float64
[35. 70. 85. 77. 87.]
Index(['A', 'B', 'C', 'D', 'E'], dtype='object')
Number
False
(5,)
5
1
float64
True

In [59]:
data=pd.Series([35,70,85,77,87],['A','B','C','D','E'],name="Number",dtype="float")
print(data.loc['C':'E'])
print(data.iloc[2])
# print(data.iloc['D']) Typerror
print()
data=pd.Series([35,70,85,77,87],name="Number",dtype="float")
print(data.loc[2:4])
print(data.iloc[0])
print(data.iloc[2:4])

C    85.0
D    77.0
E    87.0
Name: Number, dtype: float64
85.0

2    85.0
3    77.0
4    87.0
Name: Number, dtype: float64
35.0
2    85.0
3    77.0
Name: Number, dtype: float64

In [69]:
data=pd.Series([35,70,85,77,87],['A','B','C','D','E'],name="Number",dtype="float")
print(data.iloc[[2,4]])
print(data.loc[['C','E']])

C    85.0
E    87.0
Name: Number, dtype: float64
C    85.0
E    87.0
Name: Number, dtype: float64

In [118]:
data=pd.Series([35,45,85,77,87],['A','B','C','D','E'],name="Number",dtype="float")
print(data)
data.loc['C':'E']=75
print(data)
data.loc[['A','C','E']]=95
print(data)

A    35.0
B    45.0
C    85.0
D    77.0
E    87.0
Name: Number, dtype: float64
A    35.0
B    45.0
C    75.0
D    75.0
E    75.0
Name: Number, dtype: float64
A    95.0
B    45.0
C    95.0
D    75.0
E    95.0
Name: Number, dtype: float64

In [119]:
data=[[1,2,3],[4,5,6],[7,8,9]]
df=pd.DataFrame(data)
print(df)

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [122]:
data={"A":{'P':1,'Q':1},'B':{'R':1,'S':1}}
df=pd.DataFrame(data)
print(df)

     A    B
P  1.0  NaN
Q  1.0  NaN
R  NaN  1.0
S  NaN  1.0

In [124]:
data=[{'P':1},{'B':2},{"C":3}]
df=pd.DataFrame(data)
print(df)

     P    B    C
0  1.0  NaN  NaN
1  NaN  2.0  NaN
2  NaN  NaN  3.0

In [126]:
data={'A':[1,2,3,4],
      'B':['P','Q','R','S']}
df=pd.DataFrame(data)
print(df)

   A  B
0  1  P
1  2  Q
2  3  R
3  4  S

In [127]:
data={'A':[1,2,3,4],
      'B':['P','Q','R','S']}
df=pd.DataFrame(data,index=['x','y','z','w'])
print(df)

   A  B
x  1  P
y  2  Q
z  3  R
w  4  S

In [10]:
import pandas as pd
data={'Name':["Dhoni","Rohit","Virat","Gill"],
      'Run':[12000,11000,3000,4200],
     'Average':[59.5,48.7,51.2,45.3]}
df=pd.DataFrame(data,index=['A','B','C','D'])
print(df)

    Name    Run  Average
A  Dhoni  12000     59.5
B  Rohit  11000     48.7
C  Virat   3000     51.2
D   Gill   4200     45.3

In [11]:
import pandas as pd
data={'Name':["Dhoni","Rohit","Virat","Gill"],
      'Run':[12000,11000,3000,4200],
     'Average':[59.5,48.7,51.2,45.3]}
df=pd.DataFrame(data,index=['A','B','C','D'])
print(df['Run'])

A    12000
B    11000
C     3000
D     4200
Name: Run, dtype: int64

In [22]:
import pandas as pd
data={'Name':["Dhoni","Rohit","Virat","Gill"],
      'Run':[12000,11000,3000,4200],
     'Average':[59.5,48.7,51.2,45.3]}
df=pd.DataFrame(data,index=['A','B','C','D'])
print(df[['Run','Average']])
print(df.shape)
print(df.ndim)
print(df.index)
print(df.columns)
print(df[1:4])
print()
print(df.loc['B':'D'])

     Run  Average
A  12000     59.5
B  11000     48.7
C   3000     51.2
D   4200     45.3
(4, 3)
2
Index(['A', 'B', 'C', 'D'], dtype='object')
Index(['Name', 'Run', 'Average'], dtype='object')
    Name    Run  Average
B  Rohit  11000     48.7
C  Virat   3000     51.2
D   Gill   4200     45.3

    Name    Run  Average
B  Rohit  11000     48.7
C  Virat   3000     51.2
D   Gill   4200     45.3

In [25]:
import pandas as pd
data={'Name':["Dhoni","Rohit","Virat","Gill"],
      'Run':[12000,11000,3000,4200],
     'Average':[59.5,48.7,51.2,45.3]}
df=pd.DataFrame(data,index=['A','B','C','D'])
df.loc['C','Run']=4000
print(df)

    Name    Run  Average
A  Dhoni  12000     59.5
B  Rohit  11000     48.7
C  Virat   4000     51.2
D   Gill   4200     45.3

In [31]:
df.set_index('Name',drop=False)
df.set_index(['Name','Average'],drop=True)
df.reset_index()

  index   Name    Run  Average
0     A  Dhoni  12000     59.5
1     B  Rohit  11000     48.7
2     C  Virat   4000     51.2
3     D   Gill   4200     45.3

In [32]:
import pandas as pd
data={'Name':["Dhoni","Rohit","Virat","Gill"],
      'Run':[12000,11000,3000,4200],
     'Average':[59.5,48.7,51.2,45.3]}
df=pd.DataFrame(data,index=['A','B','C','D'])
df["score"]=1000
df1=pd.DataFrame(data,index=['A','B','C','D'])
print(df)

    Name    Run  Average  score
A  Dhoni  12000     59.5   1000
B  Rohit  11000     48.7   1000
C  Virat   3000     51.2   1000
D   Gill   4200     45.3   1000

In [42]:
import pandas as pd
data={'Name':["Dhoni","Rohit","Virat","Gill"],
      'Run':[12000,11000,3000,4200],
     'Average':[59.5,48.7,51.2,45.3]}
df=pd.DataFrame(data,index=['A','B','C','D'])
df[(df['Run']>10000) & (df['Average']>50)]

    Name    Run  Average
A  Dhoni  12000     59.5

In [43]:
df[['Run','Average']][(df['Run']>10000) & (df['Average']>50)]

     Run  Average
A  12000     59.5

In [62]:
df.sort_values("Average",axis=0,ascending=False)

    Name    Run  Average
A  Dhoni  12000     59.5
C  Virat   3000     51.2
B  Rohit  11000     48.7
D   Gill   4200     45.3

In [68]:
df.sort_index(axis=0,ascending=False)

    Name    Run  Average
D   Gill   4200     45.3
C  Virat   3000     51.2
B  Rohit  11000     48.7
A  Dhoni  12000     59.5

In [78]:
data={'Name':["Dhoni","Rohit","Virat","Gill"],
      'Run':[12000,3000,3000,4200],
     'Average':[59.5,48.7,51.7,45.3]}
df=pd.DataFrame(data,index=['A','B','C','D'])
df.sort_values(['Run','Average'],axis=0,ascending=[True,False])

    Name    Run  Average
C  Virat   3000     51.7
B  Rohit   3000     48.7
D   Gill   4200     45.3
A  Dhoni  12000     59.5

In [79]:
df.sort_values(['Run','Average'],axis=0,ascending=[True,False],ignore_index=True)

    Name    Run  Average
0  Virat   3000     51.7
1  Rohit   3000     48.7
2   Gill   4200     45.3
3  Dhoni  12000     59.5

In [82]:
df.sort_values(['Run','Average'],axis=0,ascending=[True,False],inplace=False)

    Name    Run  Average
C  Virat   3000     51.7
B  Rohit   3000     48.7
D   Gill   4200     45.3
A  Dhoni  12000     59.5

      mpg  cylinders  displacement horsepower  weight  acceleration  \
0    18.0          8         307.0        130    3504          12.0
1    15.0          8         350.0        165    3693          11.5
2    18.0          8         318.0        150    3436          11.0
3    16.0          8         304.0        150    3433          12.0
4    17.0          8         302.0        140    3449          10.5
..    ...        ...           ...        ...     ...           ...
393  27.0          4         140.0         86    2790          15.6
394  44.0          4          97.0         52    2130          24.6
395  32.0          4         135.0         84    2295          11.6
396  28.0          4         120.0         79    2625          18.6
397  31.0          4         119.0         82    2720          19.4

     model year  origin                   car name
0            70       1  chevrolet chevelle malibu
1            70       1          buick skylark 320
2            70       1         plymouth satellite
3            70       1              amc rebel sst
4            70       1                ford torino
..          ...     ...                        ...
393          82       1            ford mustang gl
394          82       2                  vw pickup
395          82       1              dodge rampage
396          82       1                ford ranger
397          82       1                 chevy s-10

[398 rows x 9 columns]