In [3]:
import pandas as pd
import numpy as np

In [40]:
data = {
    'Dept':['IT','IT','HR','HR','FIN','IT'],
    'Emp':['A','B','C','D','E','F'],
    'Sal':[5000,6000,4500,4800,7000,5500],
    'Exp':[2,3,1,2,5,4]
}
df = pd.DataFrame(data)

In [41]:
df

  Dept Emp   Sal  Exp
0   IT   A  5000    2
1   IT   B  6000    3
2   HR   C  4500    1
3   HR   D  4800    2
4  FIN   E  7000    5
5   IT   F  5500    4

In [9]:
df.groupby('Dept').head()

  Dept Emp   Sal  Exp
0   IT   A  5000    2
1   IT   B  6000    3
2   HR   C  4500    1
3   HR   D  4800    2
4  FIN   E  7000    5
5   IT   F  5500    4

In [10]:
df.groupby('Dept').sample()

  Dept Emp   Sal  Exp
4  FIN   E  7000    5
3   HR   D  4800    2
1   IT   B  6000    3

In [11]:
len(df.groupby('Dept'))

3

In [12]:
df.groupby('Dept').sum()

      Emp    Sal  Exp
Dept
FIN     E   7000    5
HR     CD   9300    3
IT    ABF  16500    9

In [13]:
df.groupby('Dept')[['Sal','Exp']].sum()

        Sal  Exp
Dept
FIN    7000    5
HR     9300    3
IT    16500    9

In [14]:
df.groupby('Dept').max()

     Emp   Sal  Exp
Dept
FIN    E  7000    5
HR     D  4800    2
IT     F  6000    4

In [16]:
df.groupby('Dept').describe()

       Sal                                                               Exp  \
     count    mean         std     min     25%     50%     75%     max count
Dept
FIN    1.0  7000.0         NaN  7000.0  7000.0  7000.0  7000.0  7000.0   1.0
HR     2.0  4650.0  212.132034  4500.0  4575.0  4650.0  4725.0  4800.0   2.0
IT     3.0  5500.0  500.000000  5000.0  5250.0  5500.0  5750.0  6000.0   3.0


     mean       std  min   25%  50%   75%  max
Dept
FIN   5.0       NaN  5.0  5.00  5.0  5.00  5.0
HR    1.5  0.707107  1.0  1.25  1.5  1.75  2.0
IT    3.0  1.000000  2.0  2.50  3.0  3.50  4.0

In [19]:
df.groupby('Dept').size()

Dept
FIN    1
HR     2
IT     3
dtype: int64

In [18]:
df.groupby('Dept').min()

     Emp   Sal  Exp
Dept
FIN    E  7000    5
HR     C  4500    1
IT     A  5000    2

In [20]:
df.groupby('Dept').nunique()

      Emp  Sal  Exp
Dept
FIN     1    1    1
HR      2    2    2
IT      3    3    3

In [42]:
df

  Dept Emp   Sal  Exp
0   IT   A  5000    2
1   IT   B  6000    3
2   HR   C  4500    1
3   HR   D  4800    2
4  FIN   E  7000    5
5   IT   F  5500    4

In [31]:
total = df.groupby('Dept')['Sal'].sum()

In [37]:
total.apply(lambda x :'good' if x > 10000 else 'poor')

Dept
FIN    poor
HR     poor
IT     good
Name: Sal, dtype: object

In [43]:
df

  Dept Emp   Sal  Exp
0   IT   A  5000    2
1   IT   B  6000    3
2   HR   C  4500    1
3   HR   D  4800    2
4  FIN   E  7000    5
5   IT   F  5500    4

In [44]:
df.groupby('Dept').agg({'Sal':['min','max','mean'],'Exp':['mean']})

       Sal                Exp
       min   max    mean mean
Dept
FIN   7000  7000  7000.0  5.0
HR    4500  4800  4650.0  1.5
IT    5000  6000  5500.0  3.0

In [46]:
df.groupby('Dept').nth(1)

  Dept Emp   Sal  Exp
1   IT   B  6000    3
3   HR   D  4800    2

In [50]:
for i in df.groupby('Dept',sort = False):
    print(i)

('IT',   Dept Emp   Sal  Exp
0   IT   A  5000    2
1   IT   B  6000    3
5   IT   F  5500    4)
('HR',   Dept Emp   Sal  Exp
2   HR   C  4500    1
3   HR   D  4800    2)
('FIN',   Dept Emp   Sal  Exp
4  FIN   E  7000    5)

In [53]:
df.groupby(['Dept','Exp']).groups

{('FIN', 5): [4], ('HR', 1): [2], ('HR', 2): [3], ('IT', 2): [0], ('IT', 3): [1], ('IT', 4): [5]}