In [1]:
import pandas as pd
import numpy as np

C:\Users\LJENG\AppData\Roaming\Python\Python38\site-packages\pandas\core\computation\expressions.py:20: UserWarning: Pandas requires version '2.7.3' or newer of 'numexpr' (version '2.7.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [2]:
df = {
    'A':[np.nan,2,3,4,np.nan],
    'B':[np.nan,5,6,7,8],
    'C':[np.nan,7,8,np.nan,9]
}
df = pd.DataFrame(df)
df

     A    B    C
0  NaN  NaN  NaN
1  2.0  5.0  7.0
2  3.0  6.0  8.0
3  4.0  7.0  NaN
4  NaN  8.0  9.0

In [3]:
df.isnull().sum()

A    2
B    1
C    2
dtype: int64

In [4]:
df = df.fillna(df.mean())
df

     A    B    C
0  3.0  6.5  8.0
1  2.0  5.0  7.0
2  3.0  6.0  8.0
3  4.0  7.0  8.0
4  3.0  8.0  9.0

In [5]:
df['A'] = df['A'].fillna(df['A'].median())
df

     A    B    C
0  3.0  6.5  8.0
1  2.0  5.0  7.0
2  3.0  6.0  8.0
3  4.0  7.0  8.0
4  3.0  8.0  9.0

In [6]:
df['D'] = ['V','V','H','A',np.nan]
df

     A    B    C    D
0  3.0  6.5  8.0    V
1  2.0  5.0  7.0    V
2  3.0  6.0  8.0    H
3  4.0  7.0  8.0    A
4  3.0  8.0  9.0  NaN

In [7]:
df['D'] = df['D'].fillna(df['D'].mode()[0])
df

     A    B    C  D
0  3.0  6.5  8.0  V
1  2.0  5.0  7.0  V
2  3.0  6.0  8.0  H
3  4.0  7.0  8.0  A
4  3.0  8.0  9.0  V

In [8]:
df['D'].mode()

0    V
Name: D, dtype: object

In [9]:
df['B'] = df['B'].fillna(7)
df

     A    B    C  D
0  3.0  6.5  8.0  V
1  2.0  5.0  7.0  V
2  3.0  6.0  8.0  H
3  4.0  7.0  8.0  A
4  3.0  8.0  9.0  V

In [10]:
df

     A    B    C  D
0  3.0  6.5  8.0  V
1  2.0  5.0  7.0  V
2  3.0  6.0  8.0  H
3  4.0  7.0  8.0  A
4  3.0  8.0  9.0  V

In [11]:
df.dropna()

     A    B    C  D
0  3.0  6.5  8.0  V
1  2.0  5.0  7.0  V
2  3.0  6.0  8.0  H
3  4.0  7.0  8.0  A
4  3.0  8.0  9.0  V

In [12]:
df.dropna(axis = 1)

     A    B    C  D
0  3.0  6.5  8.0  V
1  2.0  5.0  7.0  V
2  3.0  6.0  8.0  H
3  4.0  7.0  8.0  A
4  3.0  8.0  9.0  V

In [13]:
df.dropna(how = 'all')

     A    B    C  D
0  3.0  6.5  8.0  V
1  2.0  5.0  7.0  V
2  3.0  6.0  8.0  H
3  4.0  7.0  8.0  A
4  3.0  8.0  9.0  V

In [14]:
df

     A    B    C  D
0  3.0  6.5  8.0  V
1  2.0  5.0  7.0  V
2  3.0  6.0  8.0  H
3  4.0  7.0  8.0  A
4  3.0  8.0  9.0  V

In [15]:
df.dropna(thresh=3)

     A    B    C  D
0  3.0  6.5  8.0  V
1  2.0  5.0  7.0  V
2  3.0  6.0  8.0  H
3  4.0  7.0  8.0  A
4  3.0  8.0  9.0  V

In [16]:
df

     A    B    C  D
0  3.0  6.5  8.0  V
1  2.0  5.0  7.0  V
2  3.0  6.0  8.0  H
3  4.0  7.0  8.0  A
4  3.0  8.0  9.0  V

In [17]:
df.dropna(subset = ['B','C'], how = 'all')

     A    B    C  D
0  3.0  6.5  8.0  V
1  2.0  5.0  7.0  V
2  3.0  6.0  8.0  H
3  4.0  7.0  8.0  A
4  3.0  8.0  9.0  V

In [18]:
df

     A    B    C  D
0  3.0  6.5  8.0  V
1  2.0  5.0  7.0  V
2  3.0  6.0  8.0  H
3  4.0  7.0  8.0  A
4  3.0  8.0  9.0  V

In [19]:
df.drop(4)

     A    B    C  D
0  3.0  6.5  8.0  V
1  2.0  5.0  7.0  V
2  3.0  6.0  8.0  H
3  4.0  7.0  8.0  A

In [20]:
df.drop('A',axis=1)

     B    C  D
0  6.5  8.0  V
1  5.0  7.0  V
2  6.0  8.0  H
3  7.0  8.0  A
4  8.0  9.0  V

In [21]:
data = {
    'A':[1,1,4,4,7],
    'B':[2,2,2,2,3],
    'C':[3,3,3,5,2]
}
df = pd.DataFrame(data)
df

   A  B  C
0  1  2  3
1  1  2  3
2  4  2  3
3  4  2  5
4  7  3  2

In [22]:
df.duplicated().sum()

1

In [23]:
df.duplicated(subset=['B']).sum()

3

In [24]:
df.duplicated(subset=['B','C']).sum()

2

In [25]:
df.duplicated(subset=['A','C']).sum()

1

In [26]:
df.drop_duplicates()

   A  B  C
0  1  2  3
2  4  2  3
3  4  2  5
4  7  3  2

In [27]:
df.drop_duplicates(keep = 'last',subset=['B','C'])

   A  B  C
2  4  2  3
3  4  2  5
4  7  3  2

In [42]:
data = {
    'C':['Q','P','J','T'],
    'A':[3,5,5,7],
    'B':[6,5,8,9]
}
df = pd.DataFrame(data)

In [43]:
df

   C  A  B
0  Q  3  6
1  P  5  5
2  J  5  8
3  T  7  9

In [44]:
df.sort_values('C',ascending =True)

   C  A  B
2  J  5  8
1  P  5  5
0  Q  3  6
3  T  7  9

In [45]:
df.sort_values('C',ascending =False)

   C  A  B
3  T  7  9
0  Q  3  6
1  P  5  5
2  J  5  8

In [46]:
df.sort_values('A',axis = 0)

   C  A  B
0  Q  3  6
1  P  5  5
2  J  5  8
3  T  7  9

In [47]:
df

   C  A  B
0  Q  3  6
1  P  5  5
2  J  5  8
3  T  7  9

In [49]:
df.sort_values(by=['A','C'],ascending=[True,False])

   C  A  B
0  Q  3  6
1  P  5  5
2  J  5  8
3  T  7  9

In [50]:
df.sort_values(by=['A','C'],ascending=[False,True])

   C  A  B
3  T  7  9
2  J  5  8
1  P  5  5
0  Q  3  6

In [51]:
df = df.set_index('C')

In [52]:
df

   A  B
C
Q  3  6
P  5  5
J  5  8
T  7  9

In [54]:
df.sort_index()

   A  B
C
J  5  8
P  5  5
Q  3  6
T  7  9

In [56]:
df.sort_index(axis=1,ascending=True)

   A  B
C
Q  3  6
P  5  5
J  5  8
T  7  9

In [57]:
df.sort_index(axis=1,ascending=False)

   B  A
C
Q  6  3
P  5  5
J  8  5
T  9  7

In [58]:
df

   A  B
C
Q  3  6
P  5  5
J  5  8
T  7  9

In [59]:
df.sum()

A    20
B    28
dtype: int64

In [61]:
df.sum(axis = 1)

C
Q     9
P    10
J    13
T    16
dtype: int64

In [62]:
df

   A  B
C
Q  3  6
P  5  5
J  5  8
T  7  9

In [66]:
df['A']= df['A'].mean()
df

     A  B
C
Q  5.0  6
P  5.0  5
J  5.0  8
T  5.0  9

In [67]:
data = {
    'A':[3,3,2,2,5,5,7,8,9,2,2,3]
}
df = pd.DataFrame(data)

In [68]:
df

    A
0   3
1   3
2   2
3   2
4   5
5   5
6   7
7   8
8   9
9   2
10  2
11  3

In [69]:
df['A'].quantile(0.25)

2.0

In [70]:
df['A'].quantile(0.5)

3.0

In [71]:
df['A'].quantile(0.75)

5.5